use std::path::Path;

use forgetest_core::suite::load_suite;
use forgetest_runner::calibration::calibrate_suite;

fn write_suite(root: &Path) {
    let task = root.join("tasks/fix");
    std::fs::create_dir_all(task.join("workspace/src")).unwrap();
    std::fs::create_dir_all(task.join("grader/tests")).unwrap();
    std::fs::write(
        root.join("suite.toml"),
        "schema_version=2\nid=\"suite\"\nname=\"Suite\"\n[[tasks]]\nid=\"fix\"\npath=\"tasks/fix\"\n",
    )
    .unwrap();
    std::fs::write(
        task.join("task.toml"),
        r#"schema_version = 1
id = "fix"
name = "Fix"
category = "bug_fix"
language = "rust"
prompt = "prompt.md"
workspace = "workspace"
grader = "grader"
reference_patch = "reference.patch"
timeout_secs = 60
[verifier]
checks = [
  { name = "hidden regression", kind = "fail_to_pass", command = ["cargo", "test", "--test", "hidden", "--locked"] },
  { name = "existing tests", kind = "pass_to_pass", command = ["cargo", "test", "--lib", "--locked"] },
]
timeout_secs = 60
[provenance]
kind = "authored"
license = "MIT"
"#,
    )
    .unwrap();
    std::fs::write(task.join("prompt.md"), "Fix value.").unwrap();
    std::fs::write(
        task.join("workspace/Cargo.toml"),
        "[package]\nname=\"fixture\"\nversion=\"0.1.0\"\nedition=\"2021\"\n",
    )
    .unwrap();
    std::fs::write(
        task.join("workspace/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 3\n\n[[package]]\nname = \"fixture\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        task.join("workspace/src/lib.rs"),
        "pub fn value() -> u8 { 0 }\n#[cfg(test)] mod tests { #[test] fn baseline() { assert_eq!(2 + 2, 4); } }\n",
    )
    .unwrap();
    std::fs::write(
        task.join("grader/tests/hidden.rs"),
        "use fixture::value;\n#[test] fn fixed() { assert_eq!(value(), 42); }\n",
    )
    .unwrap();
    std::fs::write(
        task.join("reference.patch"),
        r#"diff --git a/src/lib.rs b/src/lib.rs
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,2 +1,2 @@
-pub fn value() -> u8 { 0 }
+pub fn value() -> u8 { 42 }
 #[cfg(test)] mod tests { #[test] fn baseline() { assert_eq!(2 + 2, 4); } }
"#,
    )
    .unwrap();
}

#[tokio::test]
async fn calibration_proves_null_failure_and_reference_success() {
    let root = tempfile::tempdir().unwrap();
    write_suite(root.path());
    let suite = load_suite(&root.path().join("suite.toml")).unwrap();

    let report = calibrate_suite(&suite, 1024 * 1024).await.unwrap();

    assert!(report.passed());
    assert_eq!(report.tasks.len(), 1);
    assert!(!report.tasks[0].null_patch_passed);
    assert_eq!(report.tasks[0].reference_patch_passed, Some(true));
}
